name: Scheduled GET Request

on:
  schedule:
    # Suoritetaan joka 5. minuutti mutta ei tasa-ajoin
    - cron: "2-59/5 * * * *"
  workflow_dispatch: # Mahdollistaa manuaalisen käynnistyksen

jobs:
  get-request:
    runs-on: ubuntu-latest
    steps:
      - name: Aloitetaan tehtävä
        run: echo "Ajastettu GET-pyyntö käynnistyy osoitteeseen https://webhook-x19y.onrender.com/api/poll"

      - name: Lähetä GET-pyyntö ja tallenna vastaus
        run: |
          echo "$(date) - GET-pyyntö käynnistyy"
          response=$(curl -s -w "%{http_code}" -o response_body.txt https://webhook-x19y.onrender.com/api/poll)
          http_code=$(tail -n1 response_body.txt)
          response_body=$(sed '$d' response_body.txt)
          echo "Palvelimen vastaus: $response_body"
          echo "Palvelimen HTTP-vastauskoodi: $http_code"
          if [ "$http_code" -ne 200 ]; then
            echo "Varoitus: HTTP-vastauskoodi ei ole 200. Tarkista palvelin!"
          fi

      - name: Tehtävä valmis
        run: echo "$(date) - Ajastettu GET-pyyntö suoritettu."
