name: Scheduled GET Request

on:
  schedule:
    # Suoritetaan joka 5. minuutti
    - cron: "*/5 * * * *"

jobs:
  get-request:
    runs-on: ubuntu-latest
    steps:
      - name: Aloitetaan tehtävä
        run: echo "Ajastettu GET-pyyntö käynnistyy osoitteeseen https://webhook-x19y.onrender.com/api/poll"

      - name: Lähetä GET-pyyntö ja tallenna vastaus
        run: |
          echo "$(date) - GET-pyyntö käynnistyy"
          response=$(curl -s https://webhook-x19y.onrender.com/api/poll)
          echo "Palvelimen vastaus: $response"
          http_code=$(curl -o /dev/null -s -w "%{http_code}" https://webhook-x19y.onrender.com/api/poll)
          echo "Palvelimen HTTP-vastauskoodi: $http_code"
          if [ "$http_code" -ne 200 ]; then
            echo "Varoitus: HTTP-vastauskoodi ei ole 200. Tarkista palvelin!"
          fi

      - name: Tehtävä valmis
        run: echo "$(date) - Ajastettu GET-pyyntö suoritettu."
